### ISSUE TITLE
Performance of activation functions

### ISSUE THREAD

**Issue by julien-c** [Swift-AI/Swift-AI#64]
I see in your code that you're computing activation in a non-vectorized way, i.e. element by element. 
I expect the performance of this to be very slow, isn't it?

Thoughts on how to vectorize the activation computation?

Thanks in advance

**Comment by collinhundley** [comment]
Hi @julien-c, this is something I've looked into as I start work on v2.0. The main issue is that most vector libraries support primitive operations on matrices (addition, multiplication, etc) but not arbitrary functions like sigmoid.

With that said, the activation functions could theoretically be broken into their primitive components to get a performance boost. I'd be interested in seeing some benchmarks on this method; I'll test it out when I get a chance. Working on GPUs can help us out here too.

**Comment by collinhundley** [comment]
Update: this hasn't been addressed directly yet, but I want to point out that [version 2.0](https://github.com/collinhundley/Swift-AI/releases) now supports custom activation functions. The chance of vectorizing custom functions is basically zero, but there's still a possibility of getting it to work on the defaults that I'd like to explore.

**Comment by collinhundley** [comment]
This has been addressed in the latest NeuralNet release. Not all activations are vectorized, but the system supports it when possible.
