### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by collinhundley** [Swift-AI/Swift-AI#77]
Swift AI needs a logo. Any artists out there willing to give it a shot?

**Comment by DavidSights** [comment]
Here's a quick sketch: http://imgur.com/a/yg9IT

**Comment by omaralbeik** [comment]
@lionbytes would you be interested in this?

**Comment by collinhundley** [comment]
@DavidSights thanks! That's a good place to start; love to hear other peoples' thoughts too.

**Comment by lionbytes** [comment]
Thanks man @omaralbeik I'll give it a shot.

**Comment by lionbytes** [comment]
# Suggested Logo & Visual Identity
![preview2](https://cloud.githubusercontent.com/assets/9406603/24930910/e745ed74-1f13-11e7-84c2-9f095601fb0f.jpg)

**Comment by calebkleveter** [comment]
Wow. Love it!

**Comment by collinhundley** [comment]
@lionbytes I really like this a lot. It looks great! Appreciate the branding info and color palette.

Love to hear other people's reactions as well. So far this has my vote :)

**Comment by lionbytes** [comment]
Thanks @collinhundley. Let's see if others can contribute with better ideas as well.

**Comment by DavidSights** [comment]
@lionbytes Wow, nice! 👏🏼

**Comment by lionbytes** [comment]
# Different Coloring
![preview3](https://cloud.githubusercontent.com/assets/9406603/24932652/3501a88a-1f1b-11e7-974e-7fd9e26ee454.jpg)

**Comment by DavidSights** [comment]
@lionbytes I like the coloring of the first one a lot more The low contrast of the gray and orange doesn't look a nice as the white and orange.

**Comment by spprichard** [comment]
Love it😍👍🏻

**Comment by calebkleveter** [comment]
I prefer the first design, with a light background.

**Comment by karlml** [comment]
Colors in first are better, the last is to much like an actual brain, too organic and darker, less bold, less striking

**Comment by collinhundley** [comment]
There are elements that I like of both, but I'd have to agree that I prefer the first one.

My only piece of feedback would be this: the font feels just a *tiny* bit heavy to me - especially the "A.I." part. I like the monospace, but my perception might be skewed by the excessive use of thin fonts these days. Does anybody else get this impression? I'm not a designer though, so take this with a grain of salt.

**Comment by DavidSights** [comment]
I was also going to comment on the font. It does feel heavy and a little blocky on the A.I. And maybe the periods for abbreviation aren't necessary? Hate to nitpick though. Generally it looks good.

**Comment by lionbytes** [comment]
Thanks @collinhundley and everyone else for the feedback. 
No problem, we can try other font options. I'll take into consideration the rest of notes too.
To be honest, I'm not entirely content with it either. I'll try some other variations..

**Comment by collinhundley** [comment]
@lionbytes excited to see what you come up with!

**Comment by omaralbeik** [comment]
@lionbytes is the man 👍

**Comment by collinhundley** [comment]
Hey @lionbytes it would be awesome to start using your work! Do you use Sketch for the designs?

**Comment by lionbytes** [comment]
Hey @collinhundley, sorry it took me a while. I wasn't entirely satisfied with the design, so I needed to find some time to enhance the look of the idea. I don't use Sketch, unfortunately, but if you decide on the logo I can provide it for you in many extensions.

**Comment by lionbytes** [comment]
## Branding Update
The brand colors remained the same. I've changed the look of the font, as recommended. I did not exactly like the way the swallow bird was overlapping the brain, it looked to me somewhat like an alien egg of some sort, or a sprout with weird colors, especially when resized to small scale. This version makes both entities more distinguishable; the bird looks larger and freer, and the brain looks more like a brain.
I hope you agree with these updates.

#### Updated Version
![swift-ai7](https://cloud.githubusercontent.com/assets/9406603/25192694/ed77d8cc-253c-11e7-92ee-c20aed6763c7.png)

#### Older Version
![swift-ai7-2](https://cloud.githubusercontent.com/assets/9406603/25192760/2c4a80f4-253d-11e7-80b7-dd1e0b02996b.png)

**Comment by collinhundley** [comment]
Hey @lionbytes it looks great! I'd love to use this - if you're ok with it, we can keep the vector designs in the repo and I'll export a jpeg for the readme page. What do you think?

**Comment by lionbytes** [comment]
Glad you liked it :) Sounds good to me, @collinhundley. I'll have the vector file ready.

**Comment by collinhundley** [comment]
@lionbytes if you have time, feel free to submit a PR with the file included in SiteAssets. Otherwise, you can email it to me and I'll update everything.

**Comment by lionbytes** [comment]
You got it.

**Comment by lionbytes** [comment]
Should I fork the project and submit the pull request from there, @collinhundley ?

**Comment by collinhundley** [comment]
@lionbytes that's probably the easiest way. That way you'll show up as a contributor as well.

**Comment by lionbytes** [comment]
Done.

**Comment by collinhundley** [comment]
@lionbytes thanks a lot for your work! I've merged #79 and will update the main Readme soon.

**Comment by lionbytes** [comment]
Thanks for the merge approval man @collinhundley. Best of luck.

**Comment by calebkleveter** [comment]
@collinhundley Will you also be using this logo for the Swift AI organization?

**Comment by collinhundley** [comment]
@calebkleveter yep I believe so! Still a bit of work to do there; I'd love to build some real branding but right now the code is my top priority.
