### ISSUE TITLE
Where I can find a Multi-Layer Feed-Forward Neural Network example?

### ISSUE THREAD

**Issue by denisb411** [Swift-AI/Swift-AI#78]
Met this framework tomorrow and I'm finding it awesome, by seeing documentation and reading what's it's  possible, but I can't find any example to learn how to use it (feed/predict things). This isn't the complete repo? Where I can find the handwriting example?

Thanks.

**Comment by collinhundley** [comment]
Hi @denisb411, we're in the process of migrating everything to the new organization account. There's a note about the example projects [here](https://github.com/Swift-AI/Swift-AI/blob/master/Documentation/Examples.md). We'll have new examples ready soon!
